main: ${mainClass}
name: ${name}
version: ${version}

description: ${description}
api-version: 1.20
load: POSTWORLD
author: alex_whit
website: https://github.com/4lex-whit/Slasher

commands:
  slasher:
    description: Manages the Slasher game
    permission: slasher
    usage: "Usage: /<command> <join|leave|start|stop>"

permissions:
  slasher.player:
    description: Allows a player to join and leave the game
    default: true
  slasher.admin:
    description: Allows a player to use all Slasher commands
    default: op
    children:
      slasher.player: true
